# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: cicd-tut

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  # The type of runner that the job will run on
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
   
   # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: 'checkout'
      uses: actions/checkout@v3
    - name: 'setup node actions'
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: 'npm'
    - run: npm i
    - run: npm test
    - run: npm run build

    - run: cp -r  ~/actions-runner/cicd-react/react-tut-test/react-tut-test/build /var/www/react-cicd

    
